server:
  port: 10002
spring:
  profiles:
    active: dev
  application:
    name: account
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
  jackson:
    default-property-inclusion: non_null
  jmx:
    enabled: false
feign:
  httpclient:
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 200
    connection-timeout: 240001
ribbon:
  ReadTimeout: 240001
  ConnectTimeout: 240001

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'